
CREATE TABLE IF NOT EXISTS MONTHLY_PROMOTIONS (
    id SERIAL PRIMARY KEY,
    month_str VARCHAR(7) NOT NULL, -- Format: YYYY-MM
    amount DECIMAL(10, 2) NOT NULL,
    receipt_path TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
